app/blog/urls.py
"""
https://docs.djangoproject.com/en/4.2/topics/http/urls/
"""
from django.contrib import admin
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('search/', views.SearchViewList.as_view(), name='search'),
    path('page/<slug:slug>/', views.PageDetailView.as_view(), name='page'),
    path('post/<slug:slug>/', views.PostDetailView.as_view(), name='post'),
    path('created_by/<int:author_id>/', views.CreatedByListView.as_view(), name='created_by'),
    path('category/<str:slug>/', views.CategoryListView.as_view(), name='category'),
    path('tag/<str:slug>/', views.TagListView.as_view(), name='tag'),
]

app/project/urls.py
"""
https://docs.djangoproject.com/en/4.2/topics/http/urls/
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('', include('site_setup.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('admin_blog_thomas/', admin.site.urls),
]


if settings.DEBUG:
    # permite que o dev tenha acesso aos arquivos enviados pelo user
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # permite que o dev tenha acesso aos arquivos estáticos
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/blog/models.py
from django.db import models
from utils.rand_slug import slugify_new
from django.contrib.auth.models import User
from utils.image import resize_image
from django_summernote.models import AbstractAttachment
from django.urls import reverse
# Create your models here.


class PostAttachment(AbstractAttachment):
    def save(self, *args, **kwargs):
        if not self.name :
            self.name = self.file.name

        current_file_name = str(self.file.name)
        super_save = super().save(*args, **kwargs)
        file_changed = False

        if self.file:
            file_changed = current_file_name != self.file.name

        if file_changed:
            resize_image(self.file, new_width=900, optimize=True, quality=70)

        return super_save


class Tag(models.Model):
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    name = models.CharField(max_length=255)
    # um texto que representa a entidade, sendo uma forma de "id"
    slug = models.SlugField(
        unique=True, default=None,
        null=True, blank=True, 
        max_length=255
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.name)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=255)
    slug = models.SlugField(
        unique=True, default=None,
        null=True, blank=True,
        max_length=255
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.name)
        
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Page(models.Model):
    class Meta:
        verbose_name = 'Page'
        verbose_name_plural = 'Pages'
    
    title = models.CharField(max_length=65)
    slug = models.SlugField(
        unique=True, default='',
        null=False, blank=True,
        max_length=255
    )
    is_published = models.BooleanField(
        default=True,
        help_text=(
            'Este campo precisa estar marcado para '
            'publicação aparecer no blog.'
        )
    )
    content = models.TextField()

    def get_absolute_url(self):
        if not self.is_published:
            return reverse('blog:index')
        return reverse("blog:page", args=(self.slug, ))

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.title)
        
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class PostManager(models.Manager):
    # self representa objects dos models
    def get_published(self):
        return self.filter(is_published=True).order_by('-pk')
    
    def get_post(self, slug):
        return self.filter(slug=slug).first()


class Post(models.Model):
    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
    
    # Como o objects é representado
    # objects = models.Manager()
    objects = PostManager()

    title = models.CharField(max_length=65)
    slug = models.SlugField(
        unique=True, default='',
        blank=True, null=False,
        max_length=65
    )
    excerpt = models.CharField(max_length=150, default='')
    is_published = models.BooleanField(
        default=True,
        help_text=(
            'Este campo precisa estar marcado para '
            'publicação aparecer no blog.'
        )
    )
    content = models.TextField()
    cover = models.ImageField(upload_to='post/Y%/%m/', blank=True, default='')
    cover_in_posts_content = models.BooleanField(
        default=True,
        help_text=(
            'Exibir a imagem de capa também dentro do '
            'conteúdo do post?'
        )
    )
    # auto_now_add x auto_now
    # atualiza uma vez só x atualiza após cada save
    created_at = models.DateTimeField(auto_now_add=True)
    # o atributo related_name substitui o nome de query set 
    # para evitar conflitos. Por exemplo, para pegar um dado
    # relacionado ao usuário, deve-se usar user.post_set.all()
    # com related_name ficaria: user.post_created_by, pois user 
    # é uma ForeignKey.
    created_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        related_name='post_created_by'
    )
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        related_name='post_updated_by'
    )
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True, default=None,
    )
    # Uma relação de muito pra muitos com Tags, pois um post 
    # pode ter muitas tags e uma Tag pode estar em muitos posts
    tags = models.ManyToManyField(Tag, blank=True, default='')

    def get_absolute_url(self):
        if not self.is_published:
            return reverse('blog:index')
        return reverse("blog:post", args=(self.slug, ))
    

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.title)
        
        current_cover_name = str(self.cover.name)
        super_save = super().save(*args, **kwargs)
        cover_changed = False

        if self.cover:
            cover_changed = current_cover_name != self.cover.name

        if cover_changed:
            resize_image(self.cover, new_width=900, optimize=True, quality=70)

        return super_save

    def __str__(self):
        return self.title
    

app/blog/views/blog_views.py
from django.shortcuts import redirect
from blog.models import Post, Page
from django.db.models import Q
from django.contrib.auth.models import User
from django.http import Http404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from typing import Any

PER_PAGE = 6

# def index(request):
#     posts = Post.objects.get_published()

#     paginator = Paginator(posts, PER_PAGE)
#     page_number = request.GET.get("page")
#     page_obj = paginator.get_page(page_number)

#     return render(
#         request,
#         'blog/pages/index.html',
#         {
#             'page_obj': page_obj,
#             'page_title': 'Home -',
#         }
#     )


class PostListView(ListView):
    model = Post
    template_name = 'blog/pages/index.html'
    context_object_name = 'posts'
    ordering = '-pk'
    paginate_by = PER_PAGE
    queryset = Post.objects.get_published()
    
    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     queryset = queryset.filter(is_published=True)
    #     return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update(
            {'page_title': 'Home -'}
        )

        return context


# def search(request):
#     search_values = request.GET.get('q', '').strip()

#     if search_values == '':
#         return redirect('blog:index')
    
#     posts = (
#         Post.objects.get_published()
#         .filter(
#             Q(title__icontains=search_values) |
#             Q(excerpt__icontains=search_values) 
#         ).order_by('-id')[:PER_PAGE]
#     )
    
#     page_title = f'{search_values[:15]} - Search - '

#     return render(
#         request,
#         'blog/pages/index.html',
#         {
#             'page_obj': posts,
#             'page_title': page_title,
#         }
#     )


class SearchViewList(PostListView):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._search_values = ''
    
    def setup(self, request, *args, **kwargs):
        self._search_values = request.GET.get('q', '').strip()
        return super().setup(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = (
            queryset
            .filter(
                Q(title__icontains=self._search_values) |
                Q(excerpt__icontains=self._search_values) 
            ).order_by('-id')
        )
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self._search_values = self.request.GET.get('q', '').strip()
        page_title = f'{self._search_values[:15]} - Search - '

        context.update(
            {
                'page_title': page_title,
                'search_value': self._search_values,
            }
        )
        
        return context
    
    def get(self, request, *args, **kwargs):

        if self._search_values == '':
            return redirect('blog:index')
        
        return super().get(request, *args, **kwargs)


# def created_by(request, author_id):
#     user = User.objects.filter(pk=author_id).first()
#     user_full_name = user.username

#     if user is None:
#         raise Http404('User not found')
    
#     if user.first_name:
#         user_full_name = f'{user.first_name} {user.last_name}'

#     page_title = 'Posts de' + user_full_name
    
#     posts = (
#         Post.objects.get_published()
#         .filter(created_by__pk=author_id)
#     )

#     paginator = Paginator(posts, PER_PAGE)
#     page_number = request.GET.get("page")
#     page_obj = paginator.get_page(page_number)

#     return render(
#         request,
#         'blog/pages/index.html',
#         {
#             'page_obj': page_obj,
#             'page_title': page_title,
#         }
#     )


class CreatedByListView(PostListView):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._temp_context: dict[str, Any] = {}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # self.kwargs pega os argumentos passados via URL
        # author_id = self.kwargs.get('author_id')
        # user = User.objects.filter(pk=author_id).first()
        user = self._temp_context.get('user')
        user_full_name = user.username
        
        if user.first_name:
            user_full_name = f'{user.first_name} {user.last_name}'

        page_title = f'Posts de {user_full_name} - '

        context.update({'page_title': page_title})

        return context
    
    def get_queryset(self):
        queryset = super().get_queryset()
        author_id = self._temp_context['user'].pk
        queryset = (
            queryset
            .filter(created_by__pk=author_id))
        return queryset

    def get(self, request, *args, **kwargs):
        author_id = self.kwargs.get('author_id')
        user = User.objects.filter(pk=author_id).first()

        if user is None:
            raise Http404()
        
        self._temp_context.update(
            {
                'author_id': author_id,
                'user': user
            }
        )

        return super().get(request, *args, **kwargs)
    

# def category_view(request, slug):
#     posts = (
#         Post.objects.get_published()
#         .filter(category__slug=slug)
#     )

#     paginator = Paginator(posts, PER_PAGE)
#     page_number = request.GET.get("page")
#     page_obj = paginator.get_page(page_number)

#     if len(posts) == 0:
#         raise Http404()

#     page_title = f'{page_obj[0].category.name} - Categoria - '

#     return render(
#         request,
#         'blog/pages/index.html',
#         {
#             'page_obj': page_obj,
#             'page_title': page_title,
#         }
#     )


class CategoryListView(PostListView):
    allow_empty = False
    
    def get_queryset(self):
        queryset = super().get_queryset()
        slug = self.kwargs.get('slug')
        queryset = queryset.filter(category__slug=slug)
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        page_title = f'{self.object_list[0].category.name} - '

        context.update(
            {
                'page_title': page_title
            }
        )

        return context


# def tag_view(request, slug):
#     posts = (
#         Post.objects.get_published()
#         .filter(tags__slug=slug)
#     )

#     paginator = Paginator(posts, PER_PAGE)
#     page_number = request.GET.get("page")
#     page_obj = paginator.get_page(page_number)

#     if len(posts) == 0:
#         raise Http404()
    
#     page_title = f'{page_obj[0].tags.first().name} - Tags - '

#     return render(
#         request,
#         'blog/pages/index.html',
#         {
#             'page_obj': page_obj,
#             'page_title': page_title,
#         }
#     )


class TagListView(PostListView):
    allow_empty = False

    def get_queryset(self):
        queryset = super().get_queryset()
        slug = self.kwargs.get('slug')
        queryset = queryset.filter(tags__slug=slug)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page_title = f'{self.object_list[0].tags.first().name} - Tags - '

        print(page_title)
        context.update(
            {
                'page_title': page_title
            }
        )

        return context


# def page_view(request, slug):
#     page = Page.objects.filter(is_published=True).filter(slug=slug).first()

#     if page is None:
#         raise Http404()

#     page_title = f'{page} - Page - '

#     return render(
#         request,
#         'blog/pages/page.html',
#         {
#             'page': page,
#             'page_title': page_title,
#         }
#     )


class PageDetailView(DetailView):
    model = Page
    template_name = 'blog/pages/page.html'
    slug_field = 'slug'
    context_object_name = 'page'
    ordering = '-pk'
    queryset = Page.objects.filter(is_published=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page = self.get_object()
        page_title = f'{page.title} - Page - '
        
        context.update(
            {
                'page_title': page_title,
            }
        )

        return context
    

# def post_view(request,slug):
#     post = Post.objects.get_post(slug)

#     if post is None:
#         raise Http404()

#     page_title = f'{post} - Post -'

#     return render(
#         request,
#         'blog/pages/post.html',
#         {
#             'post': post,
#             'page_title': page_title,
#         }
#     )


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/pages/post.html'
    slug_field = 'slug'
    context_object_name = 'post'
    queryset = Post.objects.filter(is_published=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        page_title = f'{post.title} - Post -'

        context.update(
            {
                'page_title': page_title
            }
        )

        return context

app/blog/templates/blog/pages/index.html
{% extends 'blog/base.html' %}

{% block content %}
  <main class="main-content section-wrapper">
    <div class="section-content-wide">
      <div class="section-gap">

        {% if posts %}
          <div class="card-grid">
            {% for post in posts %}
              {% include 'blog/partials/_post-card.html' with i=forloop.counter0 %}
            {% endfor %}
          </div>
        {% else %}
          <div class="not-fount center">
              <h1>Nada encontrado 😥</h1>
              <p>
                Não encontramos nada nesse link, por favor, clique em outro
                ou vá para a <a href="{% url "blog:index" %}">Home</a>
              </p>
          </div>
        {% endif %}

      </div>
    </div>
  </main>
{% endblock content %}

app/blog/templates/blog/pages/page.html
{% extends 'blog/base.html' %}

{% block content %}
  <main class="main-content section-wrapper">
    <div class="section-content-narrow">
      <div class="section-gap">
        <h1 class="center">{{ page.title }}</h1>
          {{ page.content | safe }}
      </div>
    </div>
  </main>
{% endblock content %}

app/blog/templates/blog/pages/post.html
{% extends 'blog/base.html' %} 

{% block additional_head %}
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/codemirror.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/theme/dracula.min.css">

<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/codemirror.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/python/python.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/javascript/javascript.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/htmlmixed/htmlmixed.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/css/css.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/xml/xml.min.js"></script>
{% endblock additional_head %}

{% block content %}
<main class="main-content single-post section-wrapper">
  <div class="single-post-content section-content-narrow">
    <div class="single-post-gap section-gap">

      {% if post.cover and post.cover_in_posts_content %}
        <div class="single-post-cover pb-base">
          <img class="card-cover" loading="lazy" src="{{ post.cover.url}}" alt=" Cover do post {{ post.title }}">
        </div>
      {% endif %}

      <h2 class="single-post-title pb-base center">
        {{post.title}}
      </h2>

      <div class="post-meta pb-base">
        <div class="post-meta-item">
          <a class="post-meta-link" href="{% url "blog:created_by" post.created_by.pk %}">
            <i class="fa-solid fa-user"></i>
            <span>
              {% if post.created_by.first_name %}
                {{ post.created_by.first_name }}
              {% else %}
                {{ post.created_by.username }}
              {% endif %}
            </span>
          </a>
        </div>
        <div class="post-meta-item">
          <span class="post-meta-link">
            <i class="fa-solid fa-calendar-days"></i>
            <span>
              {{ post.created_at | date:'d/m/Y \à\s H:i' }}
            </span>
          </span>
        </div>

        {% if post.category %}
          <div class="post-meta-item">
            <a class="post-meta-link" href="{% url "blog:category" post.category.slug %}">
              <i class="fa-solid fa-tag"></i>
              <span>
                {{ post.category }}
              </span>
            </a>
          </div>
        {% endif %}

      </div>
      
      <p class="single-post-excerpt pb-base">
        {{ post.excerpt | safe }}
      </p>

      <div class="separator"></div>

      <div class="single-post-content">
        {{ post.content | safe }} 
        
        {% if post.tags.exists %}
        <div class="post-tags">
          <span>Tags: </span>
          
          {% for tag in post.tags.all  %}
          <a class="post-tag-link" href="{% url "blog:tag" tag.slug %}">
            <i class="fa-solid fa-link"></i>
            <span>{{ tag.name }}</span>
          </a>
          {% endfor %}

        </div>
        {% endif %}

      </div>
    
    </div>
  </div>
</main>

{% endblock content %}